name: task_manager_client
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6  # iOS-style icons
  http: ^1.3.0  # For API calls
  provider: ^6.1.0  # State management
  shared_preferences: ^2.2.2  # Persistent storage
  flutter_secure_storage: ^9.0.0  # Secure storage for sensitive data
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lint rules

flutter:
  uses-material-design: true  # Enables Material Icons

  # Define assets (uncomment and add if needed)
  # assets:
  #   - assets/images/example.png
  #   - assets/icons/icon.png

  # Custom fonts (uncomment and configure if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
